717
AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent pull request #734
Opened 2024-11-04 05:16 UTC by FrancescoVassalli

address #717

2024-11-04 06:00 UTC, surapuramakhil requested changes
@FrancescoVassalli request to address this changes.

2024-11-04 06:53 UTC, cjbbb commented
When submitting a PR, you can also add a more detailed description of the changes to help us locate them quickly.

2024-11-07 18:09 UTC, FrancescoVassalli commented on src/ai_hawk/linkedIn_easy_applier.py
> +                file_path_pdf = os.path.join(folder_path, f"CV_{job.company}.pdf")
The candidate name does not seem to be easily accessible here

2024-11-07 19:29 UTC, sarob commented
**not sarcastic** is this a priority to spend time on?

2024-11-07 19:31 UTC, sarob commented on src/ai_hawk/linkedIn_easy_applier.py
> +                file_path_pdf = os.path.join(folder_path, f"CV_{job.company}.pdf")
including candidate name seems redundant doesn't it?

2024-11-07 23:08 UTC, FrancescoVassalli commented
> **not sarcastic** is this a priority to spend time on?

I think the UNIX time in the filename is important to take out because anti-bot operations could look for that

2024-11-08 14:08 UTC, surapuramakhil commented on src/ai_hawk/linkedIn_easy_applier.py
> +                file_path_pdf = os.path.join(folder_path, f"CV_{job.company}.pdf")
it helps hiring companies. CV with candidate name is for uploading in job portal. They do get a bunch of CV files. more professional way

for tracking / logs of Job applicants it should be CV with job ID/details like company & position

2024-11-08 14:09 UTC, surapuramakhil commented
> > **not sarcastic** is this a priority to spend time on?
> 
> I think the UNIX time in the filename is important to take out because anti-bot operations could look for that

💯 %

2024-11-11 17:29 UTC, surapuramakhil commented on src/ai_hawk/linkedIn_easy_applier.py
> +        return os.path.join(folder_path, f"CV_{job.company}({version}).pdf")
why this function called create_resume when path is CV_

2024-11-12 01:00 UTC, sarob commented
I will set aside some time to check this out

2024-11-12 16:24 UTC, sarob commented
I am digging into using this code to 

1. update the new job_description json files
2. moving the CV with this new file name format to the job_description location

2024-11-19 23:16 UTC, feder-cr commented
@sarob @FrancescoVassalli hi, any updates about this?

2024-11-23 11:09 UTC, feder-cr commented
@FrancescoVassalli ?

2024-11-23 17:30 UTC, closed without merging