[BUG]: Not applying to jobs
AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent pull request #920
Opened 2024-11-23 12:52 UTC by TylorMayfield

Updated parent div as the selector has changed.

2024-11-23 13:04 UTC, pswalia2u reviewed
working, thanks

2024-11-23 13:15 UTC, joelfuller2016 commented
Still seems there is issues. it does get the jobs, but doesnt get all the job descriptions, then says no jobs to apply
[2024-11-23 081214.392DEBUG.txt](https://github.com/user-attachments/files/17879764/2024-11-23.081214.392DEBUG.txt)

2024-11-23 16:45 UTC, chakaponi commented
#905

2024-11-23 17:04 UTC, chakaponi commented
Fix doesn't work anymore. They have changed naming again
I'm going to fix it

2024-11-23 17:14 UTC, surapuramakhil commented
@TylorMayfield @chakaponi @joelfuller2016 @pswalia2u is this working? or does this PR need to close as fix won't work?

2024-11-23 17:43 UTC, surapuramakhil requested changes
Just tested this - Fix not working.

2024-11-23 22:45 UTC, farouksholanke commented
hi guys, im still having this issue. has it been fixed?

2024-11-23 23:18 UTC, joelfuller2016 commented
Looks like the jobs are being selected but the questions are not being answered when attempting to apply. The resume is not being uploaded.

2024-11-25 13:14 UTC, surapuramakhil commented
closing this PR

as https://github.com/AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent/pull/905 merged

2024-11-25 13:14 UTC, closed without merging