added co-authors
AIHawk-FOSS/Auto_Jobs_Applier_AI_Agent pull request #979
Opened 2024-12-02 00:20 UTC by divyamb08

This PR is related to "Git Co-Author - GitHub actions #892"

2024-12-02 01:46 UTC, surapuramakhil requested changes
can you also add links of CI in action, checked repo action executed history not found.

https://github.com/divyamb08/Auto_Jobs_Applier_AI_Agent/actions/workflows/add-coauthors.yml

2024-12-02 01:46 UTC, surapuramakhil commented on README.md
> +## Git Co-Authors Feature
can you move this to contributing docs

2024-12-02 02:02 UTC, surapuramakhil commented on .github/workflows/add-coauthors.yml
> +          git push --force
force pushes are restricted - it destabilizes git tree

2024-12-02 02:05 UTC, surapuramakhil commented on .github/workflows/add-coauthors.yml
> +          git push --force
you can rely on PR approved; one PR approved trigger this CI, use GitHub anonymous email (for co-authors) print that message on PR thread.

2024-12-02 23:18 UTC, surapuramakhil commented
@divyamb08 you can merge your hotfix branch into main and push those changes.

2024-12-03 01:41 UTC, divyamb08 commented
I made the necessary changes @surapuramakhil

2024-12-03 02:39 UTC, surapuramakhil commented
@divyamb08 can you test your CI/CD.

checked https://github.com/divyamb08/Auto_Jobs_Applier_AI_Agent/actions/workflows/add-coauthors.yml its empty. 

can you test it
1. do some dummy commits in feature branch / PR branch
2. raise Pull request & approve that pull request (see triggered actions and its results)
3. merge Pull request, then see git log.

2024-12-03 08:29 UTC, closed without merging